name: "hamster Frontend"
on:
  push:
    branches:
      - master
      - develop

jobs:
  package:
    strategy:
      matrix:
        platform: [ ubuntu-latest,windows-latest,macos-latest ]
        go-version: [ 1.19 ]
        node-version: [18]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # You may need to manually build you frontend manually here, unless you have configured frontend build and install commands in wails.json.
